# Generated by Django 3.2.7 on 2021-10-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key_created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
